# Feature Selection
### Test different algorithmic functions to see which set of features will yeild better accuracy without overfitting the model. It will also reduce training time because of less data to process.

In [2]:
import pandas as pd 
import numpy as np 

## Extra Tree Classifier
Feature Importance with Bagged decision trees like Random Forest and Extra Trees can be used to esmiate the importance of features. 

Learn more about the [ExtraTreesClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html) class in the scikit-learn API.

In [8]:
# Read in the csv file
df = pd.read_csv('../data/exoplanet_data.csv')
df = df.dropna(axis='columns', how='all')
print(df.columns)
df.head()

Index(['koi_disposition', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co',
       'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2',
       'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact',
       'koi_impact_err1', 'koi_impact_err2', 'koi_duration',
       'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1',
       'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2',
       'koi_teq', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2',
       'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff', 'koi_steff_err1',
       'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2',
       'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec',
       'koi_kepmag'],
      dtype='object')


koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

In [47]:
# Feature extraction, bind class to an object
# n_estimators are the number of trees in the forest
model1 = ExtraTreesClassifier(n_estimators=10)
# Fit the arrays with the model
model1.fit(X,y)
print('The following is a scaled score of the features at n_estimators=10')
print(model.feature_importances_)

The following is a scaled score of the features at n_estimators=10
[0.13529846 0.16541872 0.12979329 0.04708777 0.0195375  0.01478677
 0.0153534  0.01220135 0.0209395  0.023102   0.01201981 0.01151099
 0.00956523 0.01719395 0.02967806 0.02664136 0.02140882 0.01214155
 0.01185653 0.012489   0.01162835 0.0113699  0.01568997 0.00973773
 0.0092699  0.00845838 0.03284808 0.00930861 0.01020008 0.01959437
 0.0195308  0.01072367 0.00995833 0.01427395 0.00823315 0.01183016
 0.00856637 0.01085899 0.01019785 0.00969731]


In [36]:
# Feature extraction, bind class to an object
# n_estimators are the number of trees in the forest
model2 = ExtraTreesClassifier(n_estimators=100)
# Fit the arrays with the model
model2.fit(X,y)
print('The following is a scaled score of the features at n_estimators=100')
print(model.feature_importances_)

The following is a scaled score of the features at n_estimators=100
[0.13529846 0.16541872 0.12979329 0.04708777 0.0195375  0.01478677
 0.0153534  0.01220135 0.0209395  0.023102   0.01201981 0.01151099
 0.00956523 0.01719395 0.02967806 0.02664136 0.02140882 0.01214155
 0.01185653 0.012489   0.01162835 0.0113699  0.01568997 0.00973773
 0.0092699  0.00845838 0.03284808 0.00930861 0.01020008 0.01959437
 0.0195308  0.01072367 0.00995833 0.01427395 0.00823315 0.01183016
 0.00856637 0.01085899 0.01019785 0.00969731]


In [44]:
# Rank the outcomes by n_estimators
feature_num = np.arange(1, 41, 1)
dict = {
    'feature_num' : feature_num,
    'feature name' : df.columns[1:],
    'n=10' : model1.feature_importances_, 
    'n=100' : model2.feature_importances_}
etc_rank = pd.DataFrame(dict)
etc_rank.sort_values(by='n=100', ascending=False).head(10)

feature_num       feature name      n=10     n=100
1             2      koi_fpflag_ss  0.184764  0.170404
0             1      koi_fpflag_nt  0.132146  0.130664
2             3      koi_fpflag_co  0.124189  0.130066
3             4      koi_fpflag_ec  0.060071  0.048735
26           27      koi_model_snr  0.021988  0.035516
15           16  koi_duration_err2  0.029898  0.027527
14           15  koi_duration_err1  0.023821  0.026958
16           17          koi_depth  0.023751  0.024574
8             9   koi_time0bk_err1  0.019330  0.021142
9            10   koi_time0bk_err2  0.020631  0.020783

## Univariate Selection
Statistical tests can be used to select those features that have the strongest relationship with the output variable.

The scikit-learn library provides the [SelectKBest](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest) class that can be used with a suite of different statistical tests to select a specific number of features.

Many different statistical test scan be used with this selection method. For example the ANOVA F-value method is appropriate for numerical inputs and categorical data, as we see in the Pima dataset. This can be used via the [f_classif()](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_classif.html) function. We will select the 4 best features using this method in the example below.

In [55]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X, y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[7.369e+02 1.433e+03 1.159e+03 5.761e+02 7.936e+01 6.782e+01 6.782e+01
 1.901e+01 8.222e+01 8.222e+01 2.233e+01 4.641e+01 6.841e-01 9.614e+01
 1.158e+02 1.158e+02 2.781e+02 1.609e+00 1.609e+00 3.701e+00 5.724e+00
 2.882e+00 2.767e+02 3.354e+00 6.785e+00 2.537e+00 2.318e+02 1.677e+02
 1.332e+02 6.494e+02 4.999e+02 9.147e+01 8.711e+01 2.340e+02 1.968e+01
 6.505e+01 2.490e+01 1.042e+02 4.267e+01 1.194e+01]
[[0 0 0 0 874.8 443 25.8 81 -81 -0.096]
 [0 1 0 0 10829.0 638 76.3 158 -176 -0.17600000000000002]
 [0 1 0 0 8079.2 1395 505.6 157 -174 -0.168]
 [0 0 0 0 603.3 1406 40.9 169 -211 -0.21]
 [0 0 0 0 686.0 1160 40.2 189 -232 -0.22899999999999998]]


In [46]:
from sklearn.ensemble import ExtraTreesClassifier
# Create an array from the values in the dataframe values
array = df.values
# Pull out features and labels from the columns with slice 
X= array[:, 1:]
y= array[:, 0]