# Feature Selection
### Test different algorithmic functions to see which set of features will yeild better accuracy without overfitting the model. It will also reduce training time because of less data to process.
#### Credit to Jason Brownlee's [article](https://machinelearningmastery.com/feature-selection-machine-learning-python/) for guidance

In [2]:
import pandas as pd 
import numpy as np 

## Extra Tree Classifier
Feature Importance with Bagged decision trees like Random Forest and Extra Trees can be used to esmiate the importance of features. 

Learn more about the [ExtraTreesClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html) class in the scikit-learn API.

In [8]:
# Read in the csv file
df = pd.read_csv('../data/exoplanet_data.csv')
df = df.dropna(axis='columns', how='all')
print(df.columns)
df.head()

Index(['koi_disposition', 'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co',
       'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2',
       'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact',
       'koi_impact_err1', 'koi_impact_err2', 'koi_duration',
       'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1',
       'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2',
       'koi_teq', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2',
       'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff', 'koi_steff_err1',
       'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2',
       'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec',
       'koi_kepmag'],
      dtype='object')


koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

In [47]:
# Feature extraction, bind class to an object
# n_estimators are the number of trees in the forest
model1 = ExtraTreesClassifier(n_estimators=10)
# Fit the arrays with the model
model1.fit(X,y)
print('The following is a scaled score of the features at n_estimators=10')
print(model.feature_importances_)

The following is a scaled score of the features at n_estimators=10
[0.13529846 0.16541872 0.12979329 0.04708777 0.0195375  0.01478677
 0.0153534  0.01220135 0.0209395  0.023102   0.01201981 0.01151099
 0.00956523 0.01719395 0.02967806 0.02664136 0.02140882 0.01214155
 0.01185653 0.012489   0.01162835 0.0113699  0.01568997 0.00973773
 0.0092699  0.00845838 0.03284808 0.00930861 0.01020008 0.01959437
 0.0195308  0.01072367 0.00995833 0.01427395 0.00823315 0.01183016
 0.00856637 0.01085899 0.01019785 0.00969731]


In [36]:
# Feature extraction, bind class to an object
# n_estimators are the number of trees in the forest
model2 = ExtraTreesClassifier(n_estimators=100)
# Fit the arrays with the model
model2.fit(X,y)
print('The following is a scaled score of the features at n_estimators=100')
print(model.feature_importances_)

The following is a scaled score of the features at n_estimators=100
[0.13529846 0.16541872 0.12979329 0.04708777 0.0195375  0.01478677
 0.0153534  0.01220135 0.0209395  0.023102   0.01201981 0.01151099
 0.00956523 0.01719395 0.02967806 0.02664136 0.02140882 0.01214155
 0.01185653 0.012489   0.01162835 0.0113699  0.01568997 0.00973773
 0.0092699  0.00845838 0.03284808 0.00930861 0.01020008 0.01959437
 0.0195308  0.01072367 0.00995833 0.01427395 0.00823315 0.01183016
 0.00856637 0.01085899 0.01019785 0.00969731]


In [44]:
# Rank the outcomes by n_estimators
feature_num = np.arange(1, 41, 1)
dict = {
    'feature_num' : feature_num,
    'feature name' : df.columns[1:],
    'n=10' : model1.feature_importances_, 
    'n=100' : model2.feature_importances_}
etc_rank = pd.DataFrame(dict)
etc_rank.sort_values(by='n=100', ascending=False).head(10)

feature_num       feature name      n=10     n=100
1             2      koi_fpflag_ss  0.184764  0.170404
0             1      koi_fpflag_nt  0.132146  0.130664
2             3      koi_fpflag_co  0.124189  0.130066
3             4      koi_fpflag_ec  0.060071  0.048735
26           27      koi_model_snr  0.021988  0.035516
15           16  koi_duration_err2  0.029898  0.027527
14           15  koi_duration_err1  0.023821  0.026958
16           17          koi_depth  0.023751  0.024574
8             9   koi_time0bk_err1  0.019330  0.021142
9            10   koi_time0bk_err2  0.020631  0.020783

## Univariate Selection
Statistical tests can be used to select those features that have the strongest relationship with the output variable.

The scikit-learn library provides the [SelectKBest](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest) class that can be used with a suite of different statistical tests to select a specific number of features.

Many different statistical test scan be used with this selection method. For example the ANOVA F-value method is appropriate for numerical inputs and categorical data, as we see in the Pima dataset. This can be used via the [f_classif()](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_classif.html) function. We will select the 4 best features using this method in the example below.

In [59]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
test = SelectKBest(score_func=f_classif, k=5)
fit = test.fit(X, y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[7.369e+02 1.433e+03 1.159e+03 5.761e+02 7.936e+01 6.782e+01 6.782e+01
 1.901e+01 8.222e+01 8.222e+01 2.233e+01 4.641e+01 6.841e-01 9.614e+01
 1.158e+02 1.158e+02 2.781e+02 1.609e+00 1.609e+00 3.701e+00 5.724e+00
 2.882e+00 2.767e+02 3.354e+00 6.785e+00 2.537e+00 2.318e+02 1.677e+02
 1.332e+02 6.494e+02 4.999e+02 9.147e+01 8.711e+01 2.340e+02 1.968e+01
 6.505e+01 2.490e+01 1.042e+02 4.267e+01 1.194e+01]
[[0 0 0 0 81]
 [0 1 0 0 158]
 [0 1 0 0 157]
 [0 0 0 0 169]
 [0 0 0 0 189]]


In [62]:
dict = {
    'feature_num' : feature_num,
    'feature_name' : df.columns[1:],
    'fit_scores' : fit.scores_
    }
etc_rank = pd.DataFrame(dict)
etc_rank.sort_values(by='fit_scores', ascending=False).head(10)

feature_num    feature_name   fit_scores
1             2   koi_fpflag_ss  1432.706256
2             3   koi_fpflag_co  1159.458615
0             1   koi_fpflag_nt   736.896271
29           30  koi_steff_err1   649.421795
3             4   koi_fpflag_ec   576.060340
30           31  koi_steff_err2   499.942313
16           17       koi_depth   278.062703
22           23         koi_teq   276.736364
33           34  koi_slogg_err2   234.049828
26           27   koi_model_snr   231.814329

## Recursive Feature Elimination
The Recursive Feature Elimination (or RFE) works by recursively removing attributes and building a model on those attributes that remain.

It uses the model accuracy to identify which attributes (and combination of attributes) contribute the most to predicting the target attribute.

You can learn more about the [RFE](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE) class in the scikit-learn documentation.

The example below uses RFE with the logistic regression algorithm to select the top 3 features. The choice of algorithm does not matter too much as long as it is skillful and consistent.

In [64]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# feature extraction
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 6)
fit = rfe.fit(X, y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 6
Selected Features: [False False False False  True False False False False False False False
 False False False False False False False  True  True  True False False
 False False False False False  True False False False False False False
 False  True False False]
Feature Ranking: [18 22 16 21  1 34 35  2 33 32 24 13 30 14 19 20 12  5  4  1  1  1  6 11
  9 10  3 25  8  1  7 26 31 29 23 28 27  1 15 17]


In [74]:
dict = {
    'feature_num' : feature_num,
    'feature_name' : df.columns[1:],
    'best_fit' : fit.support_
    }
feature_rfe = pd.DataFrame(dict)
is_true = feature_rfe['best_fit'] == True
feature_rfe[is_true]

feature_num    feature_name  best_fit
4             5      koi_period      True
19           20        koi_prad      True
20           21   koi_prad_err1      True
21           22   koi_prad_err2      True
29           30  koi_steff_err1      True
37           38              ra      True

##Principal Component Analysis
[Principal Component Analysis](https://machinelearningmastery.com/calculate-principal-component-analysis-scratch-python/) (or PCA) uses linear algebra to transform the dataset into a compressed form.

Generally this is called a data reduction technique. A property of PCA is that you can choose the number of dimensions or principal component in the transformed result.

In the example below, we use PCA and select 3 principal components.

Learn more about the [PCA](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) class in scikit-learn by reviewing the PCA API. Dive deeper into the math behind PCA on the [Principal Component Analysis Wikipedia](https://en.wikipedia.org/wiki/Principal_component_analysis) article.

In [75]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [0.848 0.132 0.012]
[[ 2.244e-09  6.082e-08  3.256e-08  5.484e-08 -1.247e-05 -4.111e-10
   4.111e-10 -6.973e-06 -2.838e-10  2.838e-10 -5.801e-08 -3.463e-07
   2.671e-08 -5.446e-07 -2.058e-08  2.058e-08 -2.576e-03 -2.651e-05
   2.651e-05  3.852e-05  3.189e-06 -7.064e-06  1.770e-03  8.492e-01
   2.500e-01 -4.651e-01 -3.421e-05 -2.340e-08 -2.165e-04 -7.142e-06
   4.967e-06 -5.892e-07  1.670e-08  9.538e-09  1.599e-05  1.399e-06
  -4.987e-06  5.539e-07 -2.887e-07 -4.588e-07]
 [-1.936e-07  2.211e-06 -6.481e-07 -3.522e-07 -9.176e-05 -6.029e-09
   6.029e-09 -3.027e-05 -2.944e-08  2.944e-08  4.351e-08 -4.875e-06
   9.046e-07  5.669e-06 -9.978e-07  9.978e-07  9.998e-01  1.436e-02
  -1.436e-02  3.227e-05  5.025e-05  2.442e-06  8.199e-04  9.640e-04
   7.649e-04 -3.366e-03  5.891e-03 -7.439e-07  1.210e-03  9.067e-05
  -1.257e-04 -6.323e-08  1.727e-07 -2.656e-08 -9.706e-07 -1.100e-08
  -4.614e-08  1.133e-06 -7.096e-07  3.119e-08]
 [-2.404e-07 -4.450e-07 -2.874e-07 -4.665e-07  7.8

In [46]:
from sklearn.ensemble import ExtraTreesClassifier
# Create an array from the values in the dataframe values
array = df.values
# Pull out features and labels from the columns with slice 
X= array[:, 1:]
y= array[:, 0]